In [1]:
#Practical tutorial on data manipulation with numpy and pandas in python by Manish Saraswat
import numpy as np

In [2]:
np.__version__

'1.19.5'

In [3]:
#create a list comprising numbers from 0 to 9
L = list(range(10))

In [6]:
#Converting integers to string - this style of handling lists is known as list comprehension
#List comprehension offers a verstile way to handle list manipulations tasks easily.  
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
[type(item) for item in L]


[int, int, int, int, int, int, int, int, int, int]

In [8]:
#Creating Arrays
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
#creating a 3 row by 5column matrix
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#creating a metrix with predefined value
np.full((3,5), 1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [11]:
#creating an array with a set sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#creating an array of even space between the given range of values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

array([[-0.49849897, -1.70661532,  0.20882624],
       [-0.68503134, -1.83295318,  0.44805596],
       [ 0.97093937,  0.03903826,  1.34025685]])

In [14]:
#create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#set a random seed
np.random.seed(0)

In [17]:
#one dimension
x1 = np.random.randint(10, size=6)

In [18]:
#two dimension
x2 = np.random.randint(10, size=(3, 4))

In [19]:
#three dimension
x3 = np.random.randint(10, size=(3, 4, 5))

In [21]:
print("x3 ndim:", x3.ndim)

x3 ndim: 3


In [22]:
print("x3 shape:", x3.shape)

x3 shape: (3, 4, 5)


In [23]:
print("x3 size:", x3.size)

x3 size: 60


In [24]:
#Array Indexing
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [25]:
#index zero
x1[0]

4

In [26]:
#fifth value
x1[4]

8

In [27]:
#get the last value
x1[-1]

4

In [28]:
#get the second last value
x1[-2]

8

In [29]:
#in a mulitdimensional array, specify row and column index
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [30]:
#first row and 2nd column value
x2[2,3]

7

In [31]:
#3rd row and last value from the 3rd column
x2[2, -1]

7

In [32]:
#replace value at 0,0 index
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [33]:
#Array slicing
x =  np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#from start to 4th position
x[:5]

array([0, 1, 2, 3, 4])

In [35]:
#from 4th position to end
x[4:]

array([4, 5, 6, 7, 8, 9])

In [36]:
# from 4th to 6th position
x[4:7]

array([4, 5, 6])

In [37]:
#return elements at even place
x[ : : 2]

array([0, 2, 4, 6, 8])

In [38]:
# return elements from first position step by two 
x[1::2]

array([1, 3, 5, 7, 9])

In [39]:
#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])